"""Initial migration: weather and wind tables

Revision ID: c19a41b270e4
Revises: 
Create Date: 2025-04-20 09:36:11.926852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19a41b270e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_id'), 'weather', ['id'], unique=False)
    op.create_table('wind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('wind_degree', sa.Integer(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Enum('N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW', 'Variable', name='winddirectionenum'), nullable=True),
    sa.Column('should_go_outside', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weather_id')
    )
    op.create_index(op.f('ix_wind_id'), 'wind', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wind_id'), table_name='wind')
    op.drop_table('wind')
    op.drop_index(op.f('ix_weather_id'), table_name='weather')
    op.drop_table('weather')
    # ### end Alembic commands ###
